// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/SignInForm.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
}

export {}
